name: Deploy VM to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          export_default_credentials: true

      - name: Configure gcloud authentication
        run: |
          gcloud auth login --brief --no-launch-browser --update-adc --quiet

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT }}
          GOOGLE_REGION: ${{ secrets.GCP_REGION }}
          GOOGLE_ZONE: ${{ secrets.GCP_ZONE }}
